const diccionario = [
    { ESPAÑOL: 'uno', RROMANÉS: 'jekh', EUSKERA: 'bat' },
    { ESPAÑOL: 'dos', RROMANÉS: 'duj', EUSKERA: 'bi' },
    { ESPAÑOL: 'tres', RROMANÉS: 'trin', EUSKERA: 'hiru' },
    { ESPAÑOL: 'cuatro', RROMANÉS: 'eshtar', EUSKERA: 'lau' },
    { ESPAÑOL: 'cinco', RROMANÉS: 'panch', EUSKERA: 'bost' },
    { ESPAÑOL: 'seis', RROMANÉS: 'shov', EUSKERA: 'sei' },
    { ESPAÑOL: 'siete', RROMANÉS: 'efta', EUSKERA: 'zazpi' },
    { ESPAÑOL: 'ocho', RROMANÉS: 'oxtó', EUSKERA: 'zortzi' },
    { ESPAÑOL: 'nueve', RROMANÉS: 'enia', EUSKERA: 'bederatzi' },
    { ESPAÑOL: 'diez', RROMANÉS: 'desh', EUSKERA: 'hamar' },
    { ESPAÑOL: 'enero', RROMANÉS: 'januará', EUSKERA: 'urtarrila' },
    { ESPAÑOL: 'febrero', RROMANÉS: 'februará', EUSKERA: 'otsaila' },
    { ESPAÑOL: 'marzo', RROMANÉS: 'kirdaraj', EUSKERA: 'martxoa' },
    { ESPAÑOL: 'abril', RROMANÉS: 'grastornaj', EUSKERA: 'apirila' },
    { ESPAÑOL: 'mayo', RROMANÉS: 'maj', EUSKERA: 'maiatza' },
    { ESPAÑOL: 'junio', RROMANÉS: 'baredivaj', EUSKERA: 'ekaina' },
    { ESPAÑOL: 'julio', RROMANÉS: 'zulaj', EUSKERA: 'uztaila' },
    { ESPAÑOL: 'agosto', RROMANÉS: 'avgústo', EUSKERA: 'abuztua' },
    { ESPAÑOL: 'septiembre', RROMANÉS: 'septémbra', EUSKERA: 'iraila' },
    { ESPAÑOL: 'octubre', RROMANÉS: 'októbra', EUSKERA: 'urria' },
    { ESPAÑOL: 'noviembre', RROMANÉS: 'novémbra', EUSKERA: 'azaroa' },
    { ESPAÑOL: 'diciembre', RROMANÉS: 'decémbra', EUSKERA: 'abendua' },
    { ESPAÑOL: 'lunes', RROMANÉS: 'lujá', EUSKERA: 'astelehena' },
    { ESPAÑOL: 'martes', RROMANÉS: 'marti', EUSKERA: 'asteartea' },
    { ESPAÑOL: 'miércoles', RROMANÉS: 'tradji', EUSKERA: 'asteazkena' },
    { ESPAÑOL: 'jueves', RROMANÉS: 'diojá', EUSKERA: 'osteguna' },
    { ESPAÑOL: 'viernes', RROMANÉS: 'parashtuj', EUSKERA: 'ostirala' },
    { ESPAÑOL: 'sábado', RROMANÉS: 'sávato', EUSKERA: 'larunbata' },
    { ESPAÑOL: 'domingo', RROMANÉS: 'kurko', EUSKERA: 'igandea' },
    { ESPAÑOL: 'rojo', RROMANÉS: 'lolo', EUSKERA: 'gorria' },
    { ESPAÑOL: 'verde', RROMANÉS: 'zeleno', EUSKERA: 'berdea' },
    { ESPAÑOL: 'blanco', RROMANÉS: 'parno', EUSKERA: 'zuria' },
    { ESPAÑOL: 'amarillo', RROMANÉS: 'galbeno', EUSKERA: 'horia' },
    { ESPAÑOL: 'azul', RROMANÉS: 'boldo', EUSKERA: 'urdina' },
    { ESPAÑOL: 'negro', RROMANÉS: 'kalo', EUSKERA: 'beltza' },
    { ESPAÑOL: 'madre', RROMANÉS: 'daj', EUSKERA: 'ama' },
    { ESPAÑOL: 'padre', RROMANÉS: 'dad', EUSKERA: 'aita' },
    { ESPAÑOL: 'hermano', RROMANÉS: 'phral', EUSKERA: 'anaia' },
    { ESPAÑOL: 'hermana', RROMANÉS: 'phen', EUSKERA: 'arreba' },
    { ESPAÑOL: 'abuela', RROMANÉS: 'phurí daj', EUSKERA: 'amona' },
    { ESPAÑOL: 'abuelo', RROMANÉS: 'phuró dad', EUSKERA: 'aitona' },
    { ESPAÑOL: 'yo', RROMANÉS: 'me', EUSKERA: 'ni' },
    { ESPAÑOL: 'tú', RROMANÉS: 'tu', EUSKERA: 'zu' },
    { ESPAÑOL: 'él', RROMANÉS: 'vov', EUSKERA: 'bera' },
    { ESPAÑOL: 'ella', RROMANÉS: 'voi', EUSKERA: 'bera' },
    { ESPAÑOL: 'nosotras', RROMANÉS: 'amen', EUSKERA: 'gu' },
    { ESPAÑOL: 'nosotros', RROMANÉS: 'amen', EUSKERA: 'gu' },
    { ESPAÑOL: 'vosotras', RROMANÉS: 'tumen', EUSKERA: 'zuek' },
    { ESPAÑOL: 'vosotros', RROMANÉS: 'tumen', EUSKERA: 'zuek' },
    { ESPAÑOL: 'ellas', RROMANÉS: 'von', EUSKERA: 'haiek' },
    { ESPAÑOL: 'ellos', RROMANÉS: 'von', EUSKERA: 'haiek' }
    // Agrega más términos aquí
];

export default diccionario;
