const diccionario = [
    { ESPAÑOL: 'uno', RROMANÉS: 'jekh' },
    { ESPAÑOL: 'dos', RROMANÉS: 'duj' },
    { ESPAÑOL: 'tres', RROMANÉS: 'trin' },
    { ESPAÑOL: 'cuatro', RROMANÉS: 'eshtar' },
    { ESPAÑOL: 'cinco', RROMANÉS: 'panch' },
    { ESPAÑOL: 'seis', RROMANÉS: 'shov' },
    { ESPAÑOL: 'siete', RROMANÉS: 'efta' },
    { ESPAÑOL: 'ocho', RROMANÉS: 'oxtó' },
    { ESPAÑOL: 'nueve', RROMANÉS: 'enia' },
    { ESPAÑOL: 'diez', RROMANÉS: 'desh' },
    { ESPAÑOL: 'enero', RROMANÉS: 'januará' },
    { ESPAÑOL: 'febrero', RROMANÉS: 'februará' },
    { ESPAÑOL: 'marzo', RROMANÉS: 'kirdaraj' },
    { ESPAÑOL: 'abril', RROMANÉS: 'grastornaj' },
    { ESPAÑOL: 'mayo', RROMANÉS: 'maj' },
    { ESPAÑOL: 'junio', RROMANÉS: 'baredivaj' },
    { ESPAÑOL: 'julio', RROMANÉS: 'zulaj' },
    { ESPAÑOL: 'agosto', RROMANÉS: 'avgústo' },
    { ESPAÑOL: 'septiembre', RROMANÉS: 'septémbra' },
    { ESPAÑOL: 'octubre', RROMANÉS: 'októbra' },
    { ESPAÑOL: 'noviembre', RROMANÉS: 'novémbra' },
    { ESPAÑOL: 'diciembre', RROMANÉS: 'decémbra' },
    { ESPAÑOL: 'lunes', RROMANÉS: 'lujá' },
    { ESPAÑOL: 'martes', RROMANÉS: 'marti' },
    { ESPAÑOL: 'miercoles', RROMANÉS: 'tradji' },
    { ESPAÑOL: 'jueves', RROMANÉS: 'diojá' },
    { ESPAÑOL: 'viernes', RROMANÉS: 'parashtuj' },
    { ESPAÑOL: 'sabado', RROMANÉS: 'sávato' },
    { ESPAÑOL: 'domingo', RROMANÉS: 'kurko' },
    { ESPAÑOL: 'rojo', RROMANÉS: 'lolo' },
    { ESPAÑOL: 'verde', RROMANÉS: 'zeleno' },
    { ESPAÑOL: 'blanco', RROMANÉS: 'parno' },
    { ESPAÑOL: 'amarillo', RROMANÉS: 'galbeno' },
    { ESPAÑOL: 'azul', RROMANÉS: 'boldo' },
    { ESPAÑOL: 'negro', RROMANÉS: 'kalo' },
    { ESPAÑOL: 'madre', RROMANÉS: 'daj' },
    { ESPAÑOL: 'padre', RROMANÉS: 'dad' },
    { ESPAÑOL: 'hermano', RROMANÉS: 'phral' },
    { ESPAÑOL: 'hermana', RROMANÉS: 'phen' },
    { ESPAÑOL: 'abuela', RROMANÉS: 'phurí daj' },
    { ESPAÑOL: 'abuelo', RROMANÉS: 'phuró dad' },
    { ESPAÑOL: 'yo', RROMANÉS: 'me' },
    { ESPAÑOL: 'tu', RROMANÉS: 'tu' },
    { ESPAÑOL: 'el', RROMANÉS: 'vov' },
    { ESPAÑOL: 'ella', RROMANÉS: 'voi' },
    { ESPAÑOL: 'nosotras', RROMANÉS: 'amen' },
    { ESPAÑOL: 'nosotros', RROMANÉS: 'amen' },
    { ESPAÑOL: 'vosotros', RROMANÉS: 'tumen' },
    { ESPAÑOL: 'vosotras', RROMANÉS: 'tumen' },
    { ESPAÑOL: 'ellas', RROMANÉS: 'von' },
    { ESPAÑOL: 'ellos', RROMANÉS: 'von' },
    // Agrega más términos aquí
];

export default diccionario;
